In [42]:
import numpy as np


In [43]:
py_list = [1,2,3,4,5]
print(py_list)
print(type(py_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [44]:
np_array = np.array(py_list)
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [45]:
python_2d_array = [[5,1,6,7,2], [1,7,5,3,9], [9,8,0,1,4]]
print(python_2d_array)
print(type(python_2d_array))


[[5, 1, 6, 7, 2], [1, 7, 5, 3, 9], [9, 8, 0, 1, 4]]
<class 'list'>


In [46]:
np_2d_array = np.array(python_2d_array)
print(np_2d_array)
print(type(np_2d_array))

[[5 1 6 7 2]
 [1 7 5 3 9]
 [9 8 0 1 4]]
<class 'numpy.ndarray'>


In [47]:
step_array = np.arange(0, 15, 2)
print(step_array)


[ 0  2  4  6  8 10 12 14]


In [48]:
step_array_2d = np.arange(0, 15).reshape(5, 3)
print(step_array_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [49]:
zero_array = np.zeros(15)
print(zero_array)

zero_array_2d = np.zeros(15).reshape(3,5)
print(zero_array_2d)

ones_array = np.ones(15)
print(ones_array)

ones_array_2d = np.ones(15).reshape(3,5)
print(ones_array_2d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
zeroint_array_2d = np.zeros(9, dtype=int).reshape(3,3)
print(zeroint_array_2d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [51]:
id_matrix_array = np.eye(5)
print(id_matrix_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
A = np.random.randint(0, 100, 20).reshape(4, 5)
print(A)

print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

[[79 19  6 98 23]
 [38 90 72  9 81]
 [78 39 25  7 84]
 [44  7 81 78 31]]
The smallest value in A is 6, and is a located at position 2
The largest value in A is 98, and is a located at position 3


In [53]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [54]:
A_B = A + B
print(A_B)
print(A-5)
print(A-B)
print(A-5)
print(A*B)
print(A*5)
print(B/A)
print(A/2)





[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44]
[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10]
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14]
[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10]
[  1   6  15  28  45  66  91 120 153 190 231 276 325 378 435]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]
[1.         1.5        1.66666667 1.75       1.8        1.83333333
 1.85714286 1.875      1.88888889 1.9        1.90909091 1.91666667
 1.92307692 1.92857143 1.93333333]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [55]:
print(np.where(F%2==0, F, F*100))
print("this happens because if the number is even then the function replace it with the same value")

[  0 100   2 300   4 500   6 700   8 900  10]
this happens because if the number is even then the function replace it with the same value


In [56]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 1
A[5]: 6
A[14]: 15


In [57]:
A[0:5] = 0
A

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
B = np.arange(50).reshape(5, 10)
B

print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')


0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


In [59]:
B[0:2, 5:7]

array([[ 5,  6],
       [15, 16]])

In [60]:
C = np.arange(50).reshape(10, 5)

print(C%3 == 0)

print((C%3 == 0).sum())

[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]
17
